# Generated by Django 3.2.12 on 2022-03-31 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0003_record_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='sensor',
        ),
        migrations.RemoveField(
            model_name='record',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='user',
        ),
        migrations.AddField(
            model_name='record',
            name='sensor_name',
            field=models.CharField(default='sensor', max_length=200),
        ),
    ]
