# Generated by Django 3.2.12 on 2022-03-31 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graph', '0004_auto_20220331_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='timestamp',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
